import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  EyeOutline,
  EyeInvisibleOutline,
  AppstoreOutline,
  UserOutline,
  SafetyCertificateOutline,
  SettingOutline,
  FileSearchOutline,
  BankOutline,
  TeamOutline,
  ShoppingOutline,
  FolderOutline,
  FileProtectOutline,
  DatabaseOutline,
  FileDoneOutline,
  LineChartOutline,
  BarChartOutline,
  /* --- profile popup icons --- */
  LogoutOutline,
  CheckOutline,
  MoonOutline,
  SunOutline,
  EllipsisOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  EyeOutline,
  EyeInvisibleOutline,
  AppstoreOutline,
  UserOutline,
  SafetyCertificateOutline,
  SettingOutline,
  FileSearchOutline,
  BankOutline,
  TeamOutline,
  ShoppingOutline,
  FolderOutline,
  FileProtectOutline,
  DatabaseOutline,
  FileDoneOutline,
  LineChartOutline,
  BarChartOutline,
  LogoutOutline,
  CheckOutline,
  MoonOutline,
  SunOutline,
  EllipsisOutline,
];
